name = input("Enter your name: ")
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Hello", name)
print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)
print("Division:", a / b)
print("Remainder:", a % b)
print(type(a))
print(type(b))